# Generated by Django 5.1.3 on 2024-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
