# Generated by Django 5.1.2 on 2024-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id1', models.IntegerField()),
                ('count', models.IntegerField()),
                ('player_type', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('FieldPlayer', 'FieldPlayer')], max_length=20)),
                ('total_stopping_shots', models.IntegerField(blank=True, null=True)),
                ('goal_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
