# Generated by Django 5.1.2 on 2024-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Football',
            new_name='Player',
        ),
    ]
